
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:${APP_CONTAINER_PORT}"
    volumes:
      - ./:/app
    networks:
      - my_network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgresql.conf:/var/lib/postgresql/postgresql_update.conf
      - ./backup:/backup 
    command: postgres -c 'config_file=/var/lib/postgresql/postgresql_update.conf'
    networks:
      - my_network

volumes:
  postgres_data:

networks:
  my_network:
    driver: bridge

  

